### ISSUE TITLE
校外 DNS 请求会返回校内 IP

### ISSUE THREAD

**Issue by heroxbd** [tuna/pdns-ldap#3]
$ nslookup jkp.tuna.tsinghua.edu.cn

Non-authoritative answer:
Name:   jkp.tuna.tsinghua.edu.cn
Address: 49.212.183.201
Name:   jkp.tuna.tsinghua.edu.cn
Address: 166.111.26.13

**Comment by heroxbd** [comment]
bug 由 commit 8eef18298e9c47f2 引入
https://github.com/tuna/pdns-ldap/commit/8eef18298e9c47f2103c75415bb736eb2056c6a0

**Comment by heroxbd** [comment]
理想的规则应是：遇到校外请求，如果记录中存在 TUNET (59.66.x.x 166.111.x.x) 以外的 IP a 则返回 a，否则返回 TUNET 的 IP.

这样可以避免现在 mirror 使用的白名单机制。

**Comment by bigeagle** [comment]
原先的规则就是这样的，但例如 aosp.tuna.tsinghua.edu.cn 所有地址都可外网访问，但 3 网段域名校内访问会计费，故改成白名单机制。

**Comment by bigeagle** [comment]
已将 jkp 加入白名单。
